package Func

import (
	"encoding/json"
	"io"
	"net/http"
)

func FetchData(url string, c interface{}) error {
	data, err := http.Get(url)
	dat, err := io.ReadAll(data.Body)
	if err != nil {
		return err
	}
	// var x AutoGenerated
	// er := json.Unmarshal(dat, &x)
	// if er != nil {
	// 	return nil, er
	// }

	// artist, er1 := http.Get(x.Artists)
	// artiste, er1 := io.ReadAll(artist.Body)
	// if er1 != nil {
	// 	return nil, er1
	// }

	er2 := json.Unmarshal(dat, &c)
	if er2 != nil {
		return er2
	}
	// fmt.Println(c.ID)
	return nil
	// fmt.Pr
}
