package Func

import (
	"encoding/json"
	"io"
	"net/http"
)

func FetchData(url string) ([]Art, error) {
	data, err := http.Get(url)
	dat, err := io.ReadAll(data.Body)
	if err != nil {
		return nil, err
	}
	var x AutoGenerated
	er := json.Unmarshal(dat, &x)
	if er != nil {
		return nil, er
	}

	artist, er1 := http.Get(x.Artists)
	artiste, er1 := io.ReadAll(artist.Body)
	if er1 != nil {
		return nil, er1
	}

	var c []Art
	er2 := json.Unmarshal(artiste, &c)
	if er2 != nil {
		return nil, er2
	}
	// fmt.Println(c.ID)
	return c, nil
	// fmt.Pr
}
