package Handle

import (
	"fmt"
	"net/http"
	"text/template"

	Func "GroupieTracker/Ressources"
)

var c Func.AutoGenerated

func Home(w http.ResponseWriter, r *http.Request) {
	temple, err := template.ParseFiles("templates/Homepage.html")
	if err != nil {
		return
	}
	er := Func.FetchData("https://groupietrackers.herokuapp.com/api", &c)
	if er != nil {
		fmt.Println(";;;;;;;")
		return
	}

	var A []Func.Art
	errr := Func.FetchData(c.Artists, &A)
	if errr != nil {
		fmt.Println(";;;;;;;")
		return
	}
	// val := r.FormValue("name1")
	// fmt.Println(val)
	err = temple.Execute(w, A)
	if err != nil {
		fmt.Println("ok")
		return
	}
}
